[build]
  command = "pnpm run build"
  publish = "dist"

[[redirects]]
  from   = "/api/*"
  to     = "https://hcsb.synology.me:6557/api/:splat"
  status = 200
  force  = true 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200